# Generated by Django 4.0.3 on 2022-04-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_dog_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='owner',
            new_name='user',
        ),
    ]
