# Generated by Django 4.0.3 on 2022-04-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_event_dog_alter_event_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dog'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vet'),
        ),
    ]
